# Generated by Django 5.0.6 on 2024-07-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(default='charlie.davis@example.com', max_length=254),
        ),
    ]
